### PR TITLE
add http access logging

### PR DESCRIPTION
**Pull request by cyril-s**
Add http access logging

### CODE REVIEW

**Comment by tcolgate** [comment]
I think access logging everything at Info might be too much of a change of behaviour, and whilst non-200s aren't strictly an error with expexp, I do think it would be reasonable to error log them from the PoV of a user actually debugging failed scrapes.

**Comment by cyril-s** [comment]
@tcolgate added `-log.level` and `-log.json` flags. Access logging goes under info level. Default is warning. Errors from exp exp while trying to proxy http go under error. What do you think?

**Comment by tcolgate** [comment]
Cool, thanks, that looks good enough.

**Comment by tcolgate** [comment]
Thanks for you're contributions and efforts, they are very much appreciated. We don't make much of of expexp internally anymore, but it does get reasonable interest and use in the community, so I'm happy to keep maintaining it. Without your efforts it would be pretty stale by now.

**Pull request merged**
