### PR TITLE
Implement the web.telemetry-path and web.proxy-path flags

### PR DESCRIPTION
**Pull request by thomasf**

### CODE REVIEW

**Comment by thomasf** [comment]
noone listening? I will probably fork this project soon unless there is some reaction...

**Comment by tcolgate** [comment]
Sorry for the delay, could you rebase, otherwise LGTM

**Comment by thomasf** [comment]
rebased.. 

Thanks for getting to these issues.

**Comment by tcolgate** [comment]
No probs, glad it's proving useful to someone else.

**Pull request merged**
