### PR TITLE
[WIP] Update build process

### PR DESCRIPTION
**Pull request by LDaneliukas**
## Updating the way that releases are packaged
I've moved the debian specific files out of the root of the repository and into `packages` - a staging area for rpm/deb/nupkg package builds.

### Windows
Added support for building a `nupkg` (Nuget) package that can be installed by Chocolatey, the primary package manager on Windows. We could think about adding some CI pipeline to deploy new versions to the public Chocolatey repository.

### Linux
Added support for building `.rpm` packages alongside the already existing `deb` variant. Changed quite a bit how the Makefile behaves, including the default action for `all` - I supposed it'd be better for us to build binaries instead of the `.deb` package.

### CODE REVIEW

**Comment by LDaneliukas** [comment]
@tcolgate could I get your initial review / ideas on this? There's still some tweaking left for the `nupkg`, but I wanted to get a head start on some feedback.

**Comment by tcolgate** [comment]
Sorry I've not got around to reviewing this, I take it you still need it?

**Comment by LDaneliukas** [comment]
We've implemented building of RPM/NuGet packages in our own CI pipeline, however, this could be benefitial to have here too, a bit more versatile and all 3 packages could be included in releases.

**Comment by LDaneliukas** [comment]
Closing this as it has gone stale.

**Pull request closed without merging**
