### PR TITLE
Add linux ARM release - fix #73

### LINKED ISSUE #73: ARM Release
Hi *,
I need for a project an ARM release, can you adjust the build and also build an ARM binary on every release?

Cheers 🍻
Richard

### PR DESCRIPTION
**Pull request by steinbrueckri**

### CODE REVIEW

**Review by tcolgate — APPROVED** [review]

**Comment by steinbrueckri** [comment]
@tcolgate Can it be that the CI need also a change? I don't see the new binary in the release. 
Br Richard 👌

**Comment by tcolgate** [comment]
Unnfortunatley the new target breaks teh release rule (we seem to be attempting to match the pattern rule and the specific rule), I'll take a look.

**Comment by tcolgate** [comment]
THing are a bit broken at the moment, I'll need to fix this up either over the weekend or on monday

**Comment by steinbrueckri** [comment]
@tcolgate 🙏🙏🙏👏

**Comment by tcolgate** [comment]
OK, think this is all working now.

**Pull request merged**
