### PR TITLE
Refactor Dockerfile for better build caching

### PR DESCRIPTION
**Pull request by AKarbas**
Also:
* Bumped build go version in Dockerfile.
* Specified image versions and sha256 tags explicitely.

### CODE REVIEW

**Comment by AKarbas** [comment]
Also please push a new image. The latest tag is currently on 0.2.6. ([link](https://hub.docker.com/r/qubitproducts/exporter_exporter/tags?page=1&ordering=last_updated))

**Comment by tcolgate** [comment]
I'd entirely forgotten that we ever pushed to docker hub TBH. I've pushed an update to 0.4.2, and we can update make to include it in the release process.

**Comment by AKarbas** [comment]
Cool. Please also update the `latest` tag.

**Comment by steinbrueckri** [comment]
any update on this?

**Comment by tcolgate** [comment]
Sorry, I've been off on leave.
I'm not actually keen on fixing the SHA sums for the images TBH. I'd rather get the updates with the base OK when we release. The file copy changes make sense.

**Comment by tcolgate** [comment]
Specific major release for golang I think (e.g. 1.16), and latest of alpine.

**Comment by tcolgate** [comment]
Thanks for the contribution, and my apologies for the delays.

**Pull request merged**
